logs: 
    - name: testLogger2
      appenders: 
          - type: 1
            level: INFO
            format: '%d{%Y-%m-%d %H:%M:%S}%T%m%n'
    - name: testLogger1
      appenders: 
          - type: 1
            level: INFO
            format: '%d{%Y-%m-%d %H:%M:%S}%T%m%n'
