logs: log
name: leileilei
jay:
    - name: zhou
    - sex: j
    - sang:
        - qu: zhou
        - ci: fang
system: 
    port: 9090
    value: 66.88
    vector:
        - 10
        - 20
    list: [30,40]
    set: [50,60,60,70]
    unset: [50,60,60,70]
    map:
        a: 10
        c: 30
    unmap:
        a: 10
        c: 30