name: leileilei
jay:
    - name: zhou
    - sex: j
    - sang:
        - qu: zhou
        - ci: fang
system: 
    port: 9090
    value: 66.88
    vector:
        - 10
        - 20
    list: [30,40]
    set: [50,60,60,70]
    unset: [50,60,60,70]
    map:
        a: 10
        c: 30
    unmap:
        a: 10
        c: 30
    person:
        name: lei
        age: 26
        sex: true
    personmap:
        lei01:
            name: lei1
            age: 18
            sex: false
        lei02:
            name: lei2
            age: 26
            sex: true
        lei03:
            name: lei3
            age: 22
            sex: true
    personmapvec:
        vec01:
            - name: vec01Per1
              age: 1
              sex: false
            - name: vec01Per1
              age: 2
              sex: true
        vec02:
            - name: vec02Per1
              age: 1
              sex: false
            - name: vec02Per2
              age: 2
              sex: false
#- type: 2
          #  level: DEBUG
          #  format: '%d%T%m%n'
          #  path: './logs/test.log'
- name: testLogger1
      appenders: 
          - type: 1
            level: INFO
            format: '%d%T%m%n'